meta_title: "Friends Challenge - TROUVE TA COURSE, INVITE TES POTES"
meta_description: "Ton site de challenge sportif entre potes"
meta_image: "banner_meta.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@CharlesdeLaCoch" # indispensable pour les Twitter Cards
